# Generated by Django 6.0.7 on 2026-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
