# Generated by Django 6.0.7 on 2026-07-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_pinned_chatmessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_role',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
