# Generated by Django 6.0.7 on 2026-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
